[project]
name = "sciarx"
version = "0.0.2"
edition = "2026"
authors = [
  { name = "Ivan Ogasawara", email = "[ivan.ogasawara@gmail.com]" }
]
requires-arx = ">=1.23.0"

[build-system]
dependencies = [
  "arxlang >=1.23.0",
]


[environment]
kind = "conda"
name = "sciarx"

[build]
src_dir = "src"
out_dir = "build"
mode = "lib"

[dependency-groups]
dev = [
  "makim",
  "pre-commit",
]
